// Generated by Frel compiler
// Module: reactive_field
// DO NOT EDIT - This file is auto-generated

import { Runtime, Key, OneOf, Everything } from '@frel/runtime';

// Callback: updates doubled when count changes
function Main$doubled$callback(runtime, subscription) {
    const count = runtime.get(subscription.target_id, "count");
    runtime.set(subscription.target_id, "doubled", count * 2);
}

// Internal binding: initializes fields and sets up subscriptions
function Main$internal_binding(runtime, closure_id) {
    // Initialize count with default value
    runtime.set(closure_id, "count", 0);

    // Initialize doubled based on count
    const count = runtime.get(closure_id, "count");
    runtime.set(closure_id, "doubled", count * 2);

    // Subscribe doubled to count changes
    runtime.subscribe(closure_id, closure_id, Key("count"), Main$doubled$callback);
}

export const Main$metadata = {
    internal_binding: Main$internal_binding,
    top_children: [],
    call_sites: {}
};

// Register metadata with runtime
export function registerMetadata(runtime) {
    runtime.register_metadata('reactive_field.Main', Main$metadata);
}
