// Generated by Frel compiler
// Module: simple_instantiate
// DO NOT EDIT - This file is auto-generated

import { Runtime, Key, OneOf, Everything } from '@frel/runtime';

// Import from testing module
import { T0$metadata } from '../../build/testing.js';

// Main$0$call_site_binding: Main -> T0
function Main$0$call_site_binding(runtime, parent_id, child_id) {
    // T0 has no parameters, nothing to bind
}

export const Main$metadata = {
    top_children: [0],
    call_sites: {
        "0": {
            blueprint: "testing.T0",
            binding: Main$0$call_site_binding
        }
    }
};

// Register metadata with runtime
export function registerMetadata(runtime) {
    // Register testing module metadata
    runtime.register_metadata('testing.T0', T0$metadata);

    // Register this module's metadata
    runtime.register_metadata('simple_instantiate.Main', Main$metadata);
}
